# -*- coding: utf-8 -*-
"""appLogger.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mcZDDbWynzULQMFpRG1DuZP9JqX7EeQz
"""

import logging

logging.basicConfig(
    level=logging.DEBUG,
    format='%(asctime)s - %(name)s - %(levelname)s - %(message)s',
    handlers=[
        logging.FileHandler('app.log'),
        logging.StreamHandler()
    ]
)

logger = logging.getLogger(__name__)

def perform_task(task_id):
    logger.info(f'Começando a tarefa {task_id}')
    try:
        if task_id == 1:
            logger.debug('Processando tarefa 1')
            logger.warning('Problema menor encontrado na tarefa 1')
        elif task_id == 2:
            logger.error('Erro ocorrido na tarefa 2')
        elif task_id == 3:
            logger.critical('Erro critico na tarefa 3')
    except Exception as e:
        logger.exception('Ocorreu uma exceção')
        raise

try:
    perform_task(1)
except RuntimeError:
    logger.critical('Falha ao começar a tarefa.')